mode: paper
exchange_id: coinbasepro
symbol: BTC/USDT
timeframe: 1h
trade_qty: 0.001
risk:
  fast: 12
  slow: 26
  risk_per_trade: 0.005
  stop_loss: 0.02
  take_profit: 0.04
limits:
  max_daily_dd: 0.02
  max_session_dd: 0.05
  max_open_trades: 1
auto:
  enabled: false
  interval_min: 60
  run_minutes: 10
  last_auto_start: null
notifications:
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    sender: ""
    password: ""
    recipients: []
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
